# Generated by Django 3.2 on 2021-12-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectureformat", "0006_rename_streaming_streamingservice_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="electronic_device",
            old_name="davice_consumption",
            new_name="device_consumption",
        ),
        migrations.RenameField(
            model_name="lecturehall",
            old_name="light_blacboard_consumption",
            new_name="light_blackboard_consumption",
        ),
        migrations.RenameField(
            model_name="transportation",
            old_name="trasport_consumption",
            new_name="transport_consumption",
        ),
        migrations.AddField(
            model_name="faculty",
            name="elec_dev_freq",
            field=models.FloatField(
                default=0,
                verbose_name="frequency of use of electronic devices by faculty",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faculty",
            name="elec_dev_freq_file",
            field=models.FileField(default=0, upload_to="data"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faculty",
            name="elec_dev_type",
            field=models.CharField(
                default=0, max_length=200, verbose_name="Device type by faculty"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faculty",
            name="elec_dev_type_file",
            field=models.FileField(default=0, upload_to="data"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faculty",
            name="elec_dev_use",
            field=models.FloatField(
                default=0, verbose_name="Use of electronic device by faculty"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faculty",
            name="elec_dev_use_file",
            field=models.FileField(default=0, upload_to="data"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faculty",
            name="faculty_name_file",
            field=models.FileField(default=0, upload_to="data"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faculty",
            name="lecture_freq_file",
            field=models.FileField(default=0, upload_to="data"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faculty",
            name="lecture_frequency",
            field=models.FloatField(
                default=0,
                verbose_name="Number of lectures attended on daily average by faculty",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faculty",
            name="live_lec",
            field=models.FloatField(
                default=0,
                verbose_name="Percentage of online lectured watched live per faculty",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faculty",
            name="live_lec_file",
            field=models.FileField(default=0, upload_to="data"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faculty",
            name="online_lec_file",
            field=models.FileField(default=0, upload_to="data"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faculty",
            name="online_lec_freq",
            field=models.FloatField(
                default=0, verbose_name="Hours per day of watching online lectures"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transportation",
            name="transport_dur_file",
            field=models.FileField(default=0, upload_to="data"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transportation",
            name="transport_duration",
            field=models.FloatField(
                default=0, verbose_name="Time spent to or from university"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transportation",
            name="transport_freq_file",
            field=models.FileField(default=0, upload_to="data"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transportation",
            name="transport_frequency",
            field=models.FloatField(
                default=0, verbose_name="Transport frequency in days per week"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transportation",
            name="transport_name_file",
            field=models.FileField(default=0, upload_to="data"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="faculty",
            name="dev_usage",
            field=models.FloatField(
                verbose_name="Usage of electronic devices (%) per faculty"
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="lec_length",
            field=models.IntegerField(
                verbose_name="Average lecture length (min) per faculty"
            ),
        ),
    ]
