# Generated by Django 3.2 on 2021-12-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectureformat", "0007_auto_20211227_1216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="survey_file",
            field=models.FileField(blank=True, null=True, upload_to="data"),
        ),
    ]
