# Generated by Django 3.2 on 2022-01-08 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lectureformat", "0011_auto_20211229_1551"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="elec_dev_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lectureformat.electronic_device",
            ),
        ),
    ]
